(cl:defpackage duckietown_msgs-srv
  (:use )
  (:export
   "GETVARIABLE"
   "<GETVARIABLE-REQUEST>"
   "GETVARIABLE-REQUEST"
   "<GETVARIABLE-RESPONSE>"
   "GETVARIABLE-RESPONSE"
   "SETFSMSTATE"
   "<SETFSMSTATE-REQUEST>"
   "SETFSMSTATE-REQUEST"
   "<SETFSMSTATE-RESPONSE>"
   "SETFSMSTATE-RESPONSE"
   "SETVALUE"
   "<SETVALUE-REQUEST>"
   "SETVALUE-REQUEST"
   "<SETVALUE-RESPONSE>"
   "SETVALUE-RESPONSE"
   "SETVARIABLE"
   "<SETVARIABLE-REQUEST>"
   "SETVARIABLE-REQUEST"
   "<SETVARIABLE-RESPONSE>"
   "SETVARIABLE-RESPONSE"
  ))

